### ISSUE TITLE
CONTRIBUTING.md

### ISSUE THREAD

**Issue by Tupuni** [pofatu/pofatu-data#11]
is the content of 

https://github.com/pofatu/pofatu-data/blob/master/CONTRIBUTING.md

supposed to be used to feed 

https://pofatu.clld.org/about 

?

**Comment by xrotwang** [comment]
Possibly. I figured the content should go into the repository as well, and
CONTRIBUTING.md is a semi-standard place to look for such info.

Tupuni <notifications@github.com> schrieb am Fr., 31. Jan. 2020, 14:48:
