### ISSUE TITLE
Curation of datasets

### ISSUE THREAD

**Issue by Tupuni** [pofatu/pofatu-data#12]
I spotted errors in the compositional data of this dataset. Is it still possible to modify the data before the first final release?

**Comment by Tupuni** [comment]
Knowing that our co-authors / contributors will be asked to review the content and might also spot similar errors after this first release but before submitting.

**Comment by xrotwang** [comment]
Yes, I think we can correct errors any time - that's the idea when curating data in a version controlled repository. We'd still have to create the first release **before** submitting the paper, but can release updates with corrections after review, or upon publication.

**Comment by Tupuni** [comment]
Ok so can pofatu-data/raw/pofatu.xlsx be curated without releasing a new version of the database?

Additionally I started a comprehensive "log file" of changes/updates made to pofatu-data/raw/pofatu.xlsx, it might be useful to share that as part of pofatu-data/doc. Would that be a good place?

**Comment by xrotwang** [comment]
Ideally, what you put into the log file should go into the commit message whenever you update pofatu.xlsx. Then it will be part of the repository, and related to the exact version of the data it belongs to.

**Comment by Tupuni** [comment]
yes of course, thank you!

**Comment by xrotwang** [comment]
The commit messages would then show up here: https://github.com/pofatu/pofatu-data/commits/master/raw/pofatu.xlsx - which is very useful.
