### ISSUE TITLE
Updates to the web app

### ISSUE THREAD

**Issue by Tupuni** [pofatu/pofatu-data#5]
- New Pofatu logo

- New Pofatu Data Submission Template 

- New Pofatu Data Submission Guidelines 

- Comments in word document:
1. Webapp header and new welcome page content
2. "About" page + content
3. Order of items in the header
4. Content at sample level
5. "Reference" page
6. Remove stats from web app

[Pofatu Data Submission Guidelines.pdf](https://github.com/pofatu/pofatu-data/files/3895604/Pofatu.Data.Submission.Guidelines.pdf)
[Pofatu Data Submission Template.xlsx](https://github.com/pofatu/pofatu-data/files/3895709/Pofatu.Data.Submission.Template.xlsx)

[Comments to Robert.docx](https://github.com/pofatu/pofatu-data/files/3895599/Comments.to.Robert.docx)

![Pofatu logo 2019 (1)](https://user-images.githubusercontent.com/42406509/69704287-65d86800-10f3-11ea-80f9-ced44a3ca28f.png)
![Pofatu logo 2019 (2)](https://user-images.githubusercontent.com/42406509/69704289-6670fe80-10f3-11ea-994a-41eb0b618b32.png)

**Comment by Tupuni** [comment]
Current content of the "About" section of the web app needs to be modified with the following text file, which provides an updated URL for citation of the Pofatu db, but still contains non definitive parts, specifically:
- the two mentions of [hyperlink] should be replaced by the actual links to the Data Submission Template and the Guidelines to data submission (that I will upload to the 'doc' file of the pofatu-data repository)
- can we distribute the following contact email: 'pofatu@shh.mpg.de'  ?

**Comment by xrotwang** [comment]
@Tupuni regarding a citation template: I'd really follow the model of (our) other databases, e.g. [AfBo](https://afbo.info/download). The citable unit is the dataset published on Zenodo, identified by DOI. The DOI in this case leads to https://zenodo.org/record/3610155 and if you scroll down,there's a recommendation "Cite as":

> Frank Seifart. (2013). cldf-datasets/afbo: AfBo: A world-wide survey of affix borrowing (Version v1.0) [Data set]. Zenodo. http://doi.org/10.5281/zenodo.3610155

It is possible to tweak this to some extent, but basically that's assembled by Zenodo - and also distributed as metadata with the DOI - so people may end up using this format anyway ...

**Comment by Tupuni** [comment]
Ok sounds good. Then we should update this section of the web app accordingly 

(and also remove the phrase "plus we will add the reference to the launching paper after it’s been published")

**Comment by Tupuni** [comment]
[Log of changes in Pofatu 30:01:20 12h10.txt](https://github.com/pofatu/pofatu-data/files/4133718/Log.of.changes.in.Pofatu.30.01.20.12h10.txt)

**Comment by Tupuni** [comment]
content of https://pofatu.clld.org/about needs to be updated:

How to cite Pofatu
To cite the database, please cite ***ADD CITATION***
Please also acknowledge the original scientists who contributed to the downloaded dataset by appropriately crediting the original data sources. We strongly encourage the publication of a secondary bibliography, which can be submitted as a supplementary material file.

How to contribute
We welcome all contributions of geochemical data on archaeological material, regardless of geographical or chrono-cultural boundaries. In order to contribute data, please download and use our Data Submission Template ***ADD HYPERLINK*** and Guidelines ***ADD HYPERLINK***

Contact us
You can contact us via email at: ***ADD ADDRESS***

**Comment by xrotwang** [comment]
Ok, I'm about to release 1.0rc1, and then will finish and release `pypofatu` and the web app.

**Comment by xrotwang** [comment]
@Tupuni so here's how a release on Zenodo looks like:
https://doi.org/10.5281/zenodo.3634436

let me know if that's ok, in particular the "cite as" info (scroll down and then on the right)
