### ISSUE TITLE
Issues with ../raw/pofatu.xlsx

### ISSUE THREAD

**Issue by Tupuni** [pofatu/pofatu-data#9]
I spotted a series of issues with the content of 'compositional data' in the raw xlsx file while manually consulting the data to prepare the fully integrated test.
See log file for a tracking of the changes
[Log of changes in Pofatu 30:01:20.txt](https://github.com/pofatu/pofatu-data/files/4133848/Log.of.changes.in.Pofatu.30.01.20.txt)

**Comment by xrotwang** [comment]
Issues are fixed.
